balena-os/balena-generic

layers/meta-balena-generic/recipes-core/images/balena-image.bbappend

This adds firmware for Intel wireless chipsets supported by the iwlwifi
driver. Tested with AX200 chipset.
Changelog-entry: balena-image: add linux-firmware-iwlwifi to generic-amd64

balena-image: add linux-firmware-iwlwifi to generic-amd64

---

layers/meta-balena-generic/recipes-core/images/balena-image.bbappend

Use the same image size as genericx86-64-ext for compatiblity. This
allows the generic-amd64 image to replace genericx86-64-ext when they
reach feature parity, without causing hostapp-update problems later.

balena-image: use the same IMAGE_ROOTFS_MAXSIZE as genericx86-64-ext

---

genericx86-64-ext.coffee

This allows leviathan tests to avoid having to unwrap flasher images.
Change-type: patch
Signed-off-by: Kyle Harding <kyle@balena.io>

genericx86-64-ext: Deploy both flasher and non-flasher artifacts

---

genericx86-64-ext.coffee

Reverts balena-os/balena-generic#53
Reverting this for now until we have the full solution ready. We don't want to accidentally publish the non-flasher images early.
Improvement: https://jel.ly.fish/improvement-expose-flasher-raw-images-dashboard-generic-dts-90f2f44

Revert "genericx86-64-ext: Deploy both flasher and non-flasher artifacts"

---

layers/meta-balena-generic/recipes-core/images/balena-image.inc
layers/meta-balena-generic/recipes-support/hostapp-update-hooks/files/999-resin-boot-cleaner
layers/meta-balena-generic/recipes-support/hostapp-update-hooks/hostapp-update-hooks.bbappend

The grub hook is required to set change the boot
partition after a HUP.
The boot-cleaner hook is copied from balena-intel
to clean the boot partition of redundant files.
Changelog-entry: hostapp-update-hooks: Install grub update hooks
Signed-off-by: Kyle Harding <kyle@balena.io>
Resolves: https://github.com/balena-os/balena-generic/issues/115

hostapp-update-hooks: Install grub update hooks

---

layers/meta-balena-generic/conf/samples/bblayers.conf.sample

Yocto classes and conf files ignore layer priorities and are parsed
in order instead.
Changelog-entry: Modify layer ordering
Signed-off-by: Alex Gonzalez <alexg@balena.io>

bblayers: Modify layer ordering

---

layers/meta-balena-generic/recipes-kernel/linux/files/generic-aarch64/0001-UBUNTU-SAUCE-no-up-add-compat_uts_machine-kernel-com.patch
layers/meta-balena-generic/recipes-kernel/linux/files/generic-aarch64/0002-HACK-Use-the-UNAME26-personality-to-return-armv6l-in.patch
layers/meta-balena-generic/recipes-kernel/linux/linux-yocto_%.bbappend

This allows to use this kernel in our ARM builder that require armv7l and armv6l machine strings to build.
Change-type: patch
Signed-off-by: Alex Gonzalez <alexg@balena.io>

meta-balena-generic: add uname26 personality patch

---

generic-amd64.coffee

We already process and upload both flasher and raw images that are explicitly labeled, but for legacy reasons, the unlabeled image is also used as the default. Upload the flasher image as the default/unlabeled artifact to remain consistent with the genericx86-64-ext DT provided in balena-intel.
Change-type: patch

generic-amd64: make flasher image default artifact

---

layers/meta-balena-generic/recipes-core/images/balena-image.bbappend

This is a 3rd party CAN driver, we want to include it in the generic device types.

balena-image: include peak driver

---

layers/meta-balena-generic/recipes-core/images/balena-image-initramfs.bbappend

Changelog-entry: Add modules required to boot from USB to initramfs

generic-aarch64: add modules for usb booting to initramfs

---

layers/meta-balena-generic/conf/machine/generic-aarch64.conf
layers/meta-balena-generic/conf/machine/generic-amd64.conf

This is used in OS development mode to enable serial consoles.
Changelog-entry: Define serial consoles for amd64 and aarch64
Signed-off-by: Alex Gonzalez <alexg@balena.io>

machine: define serial consoles for both amd64 and aarch64

---

layers/meta-balena-generic/recipes-support/resin-init/resin-init-flasher.bbappend

Changelog-entry: Add virtio devices as installation target for flasher images

flasher: add virtio device pattern

---

layers/meta-balena-generic/conf/samples/bblayers.conf.sample

Perl is required for building efitools used for
EFI boot entry configuration and secure boot,
Changelog-entry: add meta-perl to bblayers.conf
Signed-off-by: Alex Gonzalez <alexg@balena.io>

bblayers.conf.sample: add meta-perl

---

layers/meta-balena-generic/conf/machine/generic-aarch64.conf
layers/meta-balena-generic/conf/machine/generic-amd64.conf

Newer meta-balena uses the raid machine feature to include RAID support.
Changelog-entry: define raid in machine features for generic devices

machine: define raid machine feature

---

layers/meta-balena-generic/recipes-core/images/balena-image.inc

We build a separate GRUB EFI binary for secure boot, both the original and the new one need to be shipped. Flasher and HUP pull the correct variant based on whether secure boot is enabled or not.

balena-image: Include the secure boot GRUB variant in the boot partition

---

layers/meta-balena-generic/recipes-support/hostapp-update-hooks/files/999-resin-boot-cleaner

This prevents the following error and hup abort when sysfs is bind-mounted in the hostapp-update container:
mount: /sys/firmware/efi/efivars: efivarfs already mounted or mount point busy.
Changelog-entry: hostapp-update-hooks: Don't fail if efivars fs already mounted
Addresses one failure in https://github.com/balena-os/meta-balena/pull/3194

hostapp-update-hooks: Don't fail if efivars fs already mounted

---

generic-amd64-fs.coffee

This creates a new device type that uses kernel module signing.
Changelog-entry: Add new generic-amd64-fs device type for kernel module signing based on generic-amd64

generic-amd64-fs.coffee: Add new device type

---

generic-amd64-fs.coffee
layers/meta-balena-generic/conf/machine/generic-amd64-fs.conf
layers/meta-balena-generic/conf/samples/local.conf.sample

This is to resolve build and deploy pipeline issues - perviously we were breaking our pipeline conventions which created a cascade of errors
Change-type: patch

add generic-amd64-fs yocto-machine

---

kontron-come-xelx.coffee
layers/meta-balena-generic/conf/machine/kontron-come-xelx.conf
layers/meta-balena-generic/conf/samples/local.conf.sample

This creates a new device type that uses kernel module signing.
This code is hosted temporarily in this repo. The machine should have its own device repo with the Kontron BSP. When that happens, this code from here must be removed.
Changelog-entry: Add new kontron-come-xelx device type for kernel module signing based on generic-amd64

kontron-come-xelx: Add new device type

---

layers/meta-balena-generic/conf/machine/studio-automatedx86-sb.conf
layers/meta-balena-generic/conf/samples/local.conf.sample
studio-automatedx86-sb.coffee

This creates a new device type that uses kernel module signing.
Changelog-entry: Add new studio-automatedx86-sb device type for kernel module signing based on generic-amd64

studio-automatedx86-sb: Add new device type

---

layers/meta-balena-generic/recipes-core/images/balena-image.inc

At this moment meta-balena-raspberrypi overrides IMAGE_FSTYPES, which breaks the build of signed images, because we have introduced a separate image type for that use case. The override also seems unnecessary, as it sets the value to the exact same thing that meta-balena already did.
This patch removes the override and makes the devices use the definition from meta-balena, which does account for the signature split.

balena-image.inc: remove IMAGE_FSTYPES override

---

.github/workflows/generic-amd64.yml

The boot issue on EPYC processors was resolved
by bumping OMVF in the leviathan-worker container.
See: https://github.com/balena-os/leviathan-worker/pull/136
See: https://balena.fibery.io/Work/Project/Investigation-of-secure-boot-tests-not-booting-on-self-hosted-runners-1030

Remove AMD Ryzen label from generic-amd64 test matrix

---

.github/workflows/generic-aarch64.yml
.github/workflows/generic-amd64-fs.yml
.github/workflows/generic-amd64.yml
.github/workflows/kontron-come-xelx.yml
.github/workflows/studio-automatedx86-sb.yml

See: https://balena.fibery.io/Work/Project/Separate-balenaOS-signing-environments-from-deploy-environments-1049

Provide signing environments to yocto workflows

---

.github/workflows/generic-aarch64.yml
.github/workflows/generic-amd64-fs.yml
.github/workflows/generic-amd64.yml
.github/workflows/kontron-come-xelx.yml
.github/workflows/studio-automatedx86-sb.yml

This simplifies the workflow required for meta-balena testing as it can just call the device workflows directly.
Changelog-entry: Add workflow_call trigger for testing
See: https://balena.fibery.io/Work/Project/Add-workflow_call-trigger-to-device-repo-workflows-for-meta-balena-1057
See: https://balena.fibery.io/Work/Project/Add-secureboot-tests-to-meta-balena-1261

Add workflow_call trigger to each device workflow

---

.github/workflows/generic-aarch64.yml
.github/workflows/generic-amd64.yml

**Fix support for test_matrix on workflow_call**
Previously when meta-balena would provide a value for
test_matrix it was not being used.
This change allows the calling workflow to provide a custom
test matrix while still providing the multi-line default
matrix for other event types.
**Remove the AX102 requirement for secure boot tests**
The latest self-hosted runners support cpu templates
so the guests will experience a consistent feature set
supported by the host.
**Require a new "qemu-os" tag for leviathan QEMU suites**
This allows us some control over which runners are available
for long-running leviathan QEMU test suites that download large
image files.
See: https://balena.fibery.io/Work/Improvement/Require-a-new-qemu-os-tag-for-leviathan-QEMU-suites-3184
See: …

Require a new "qemu-os" tag for leviathan QEMU suites
